#!/usr/bin/env python3
"""
build_flow_charts.py
Regenerates the two data files that feed the paying-base flow charts:

  flow-data.js   -> const FLOW_MONTHLY  (Study & Trend / index.html)
                    monthly gross adds vs churn + net-growth %
  daily-flow.js  -> const DAILY_FLOW    (FACADASH / daily.html)
                    daily gross adds, grace-adjusted

BOTH series are derived from a single on-disk source, flow_grace.csv (the
grace-adjusted daily paying-flow export). Nothing here touches Snowflake.

GRACE WINDOWS (see daily_paying_flow_grace_vs_raw.sql) — deliberately different:
  * monthly (Study & Trend)   -> *_GRACE columns = 30-day grace, the company-standard churn
                                 definition (Alex + team).
  * daily   (FACADASH adds)   -> *_G3    columns = 3-day grace, a short responsive window that
                                 suits a day-over-day momentum read.
A 30-day grace censors recent churn (a merchant lapsing today is only counted 30 days later), so
the monthly series drops unsettled months — see NEWEST_MONTH_MODE below.

The monthly series uses the GRACE columns aggregated by calendar month:
    adds  = SUM(ADDS_GRACE),  churn = SUM(CHURN_GRACE),  net = adds - churn,
    base  = last FINAL_GRACE of the month,
    g%    = net / (first INITIAL_GRACE of the month) * 100   (1 decimal)
This matches the previously hand-maintained monthly_flow.json byte-for-byte
from 2022-03 onward (2022-01/02 are Chargebee-history warm-up and excluded).

A monthly_flow.json is (re)written next to the JS as a human-readable cache.

Paths are env-overridable so this runs both standalone (sandbox defaults) and
inside the GitHub Action (run.py sets FLOW_GRACE_CSV + FLOW_OUT_DIR):
  FLOW_GRACE_CSV  input daily grace CSV        (default: <here>/flow_grace.csv)
  FLOW_OUT_DIR    dir for the .js + .json out  (default: <here>)
"""
import csv, json, os, datetime, collections

HERE       = os.path.dirname(os.path.abspath(__file__))
DAILY_CSV  = os.environ.get("FLOW_GRACE_CSV", os.path.join(HERE, "flow_grace.csv"))
OUT_DIR    = os.environ.get("FLOW_OUT_DIR", HERE)
MONTH_FLOOR     = "2022-03"   # series is clean from Mar 2022; earlier = history warm-up
DAILY_TAIL_DAYS = 120         # keep daily-flow.js small; 8-week chart + lookback fits easily

# How to treat the newest calendar month on the monthly adds-vs-churn chart. The 30-day grace
# means the newest complete month still has churn inside the grace window, so its churn reads
# low and its net growth reads high until ~30 days after month end.
#   "drop"  — publish only fully-settled months (newest complete month withheld)
#   "plot"  — publish it as-is, no special treatment
NEWEST_MONTH_MODE = os.environ.get("NEWEST_MONTH_MODE", "drop")


def _load_daily():
    rows = []
    with open(DAILY_CSV, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            if r.get("DATE"):
                rows.append(r)
    rows.sort(key=lambda r: r["DATE"][:10])
    return rows


def build_monthly(rows):
    add   = collections.defaultdict(float)
    chu   = collections.defaultdict(float)
    end   = {}
    start = {}
    for r in rows:
        m = r["DATE"][:7]
        add[m] += float(r["ADDS_GRACE"])
        chu[m] += float(r["CHURN_GRACE"])
        end[m]  = float(r["FINAL_GRACE"])
        if m not in start:
            start[m] = float(r["INITIAL_GRACE"])
    monthly = []
    for m in sorted(add):
        if m < MONTH_FLOOR:
            continue
        a = int(round(add[m])); c = int(round(chu[m])); net = a - c
        g = round(net / start[m] * 100, 1) if start[m] else 0.0
        monthly.append({"m": m, "adds": a, "churn": c, "net": net,
                        "base": int(round(end[m])), "g": g})
    # cache the full monthly series (incl. the in-progress month) for inspection
    with open(os.path.join(OUT_DIR, "monthly_flow.json"), "w", encoding="utf-8") as f:
        json.dump(monthly, f)
    # the chart shows COMPLETE calendar months only (drop the current in-progress month)
    this_month = datetime.date.today().strftime("%Y-%m")
    out = [{"m": r["m"], "adds": r["adds"], "churn": r["churn"], "net": r["net"], "g": r["g"]}
           for r in monthly if r["m"] < this_month]
    # 30-day grace: the newest complete month is still settling (its last 30 days of churn have
    # not had time to register). NEWEST_MONTH_MODE decides whether it is published.
    if NEWEST_MONTH_MODE == "drop" and out:
        out = out[:-1]
    js = ("// AUTO-GENERATED by build_flow_charts.py — monthly paying-base flow (complete months).\n"
          "const FLOW_MONTHLY = " + json.dumps(out, separators=(",", ":")) + ";\n")
    with open(os.path.join(OUT_DIR, "flow-data.js"), "w", encoding="utf-8") as f:
        f.write(js)
    return len(out), (out[-1]["m"] if out else "—")


def build_daily(rows):
    daily = []
    for r in rows:
        # 3-day grace: short window, keeps the day-over-day read responsive. Falls back to the
        # 30-day column only if an older CSV without ADDS_G3 is ever reused.
        a = r.get("ADDS_G3", r.get("ADDS_GRACE"))
        if a in (None, ""):
            a = r.get("ADDS_GRACE")
        if a in (None, ""):
            continue
        daily.append({"date": r["DATE"][:10], "adds": int(round(float(a)))})
    # Drop the in-progress current day: the pull runs with D_END = CURRENT_DATE, so the last
    # row is a partial "today" whose adds are still accumulating. Plotting it makes the D-1
    # week-over-week variance read ~-100% (today's ~0 vs a full day -7d). Cut at D-1, mirroring
    # the complete-months-only rule in build_monthly.
    today = datetime.date.today().isoformat()
    daily = [d for d in daily if d["date"] < today]
    daily = daily[-DAILY_TAIL_DAYS:]
    js = ("// AUTO-GENERATED by build_flow_charts.py — daily gross adds (grace-adjusted), last "
          + str(DAILY_TAIL_DAYS) + " days.\n"
          "const DAILY_FLOW = " + json.dumps(daily, separators=(",", ":")) + ";\n")
    with open(os.path.join(OUT_DIR, "daily-flow.js"), "w", encoding="utf-8") as f:
        f.write(js)
    return len(daily), (daily[0]["date"] if daily else "—"), (daily[-1]["date"] if daily else "—")


if __name__ == "__main__":
    rows = _load_daily()
    m_n, m_last = build_monthly(rows)
    d_n, d_first, d_last = build_daily(rows)
    print(f"flow-data.js:  {m_n} complete months, through {m_last}")
    print(f"daily-flow.js: {d_n} days, {d_first} -> {d_last}")
