# Country ISO2 -> name. Keep in sync with refresh.py.
COUNTRY_NAMES = {
    "PH":"Philippines","TH":"Thailand","MX":"Mexico","ID":"Indonesia","MY":"Malaysia","VN":"Vietnam",
    "BR":"Brazil","US":"United States","SA":"Saudi Arabia","MM":"Myanmar","ES":"Spain","GB":"United Kingdom",
    "IN":"India","CO":"Colombia","AR":"Argentina","CR":"Costa Rica","ZW":"Zimbabwe","DZ":"Algeria","TW":"Taiwan",
    "LA":"Laos","TT":"Trinidad & Tobago","SG":"Singapore","HT":"Haiti","KH":"Cambodia","AE":"United Arab Emirates",
    "ZA":"South Africa","VE":"Venezuela","BD":"Bangladesh","AU":"Australia","EC":"Ecuador","GT":"Guatemala",
    "JM":"Jamaica","BE":"Belgium","JP":"Japan","EG":"Egypt","KR":"South Korea","PK":"Pakistan","NG":"Nigeria",
    "PE":"Peru","DO":"Dominican Republic","CL":"Chile","CA":"Canada","FR":"France","DE":"Germany","IT":"Italy",
    "NL":"Netherlands","PT":"Portugal","PL":"Poland","RO":"Romania","RU":"Russia","UA":"Ukraine","TR":"Turkey",
    "GR":"Greece","IE":"Ireland","CH":"Switzerland","AT":"Austria","SE":"Sweden","NO":"Norway","DK":"Denmark",
    "FI":"Finland","CZ":"Czechia","SK":"Slovakia","HU":"Hungary","BG":"Bulgaria","HR":"Croatia","RS":"Serbia",
    "SI":"Slovenia","LT":"Lithuania","LV":"Latvia","EE":"Estonia","IS":"Iceland","LU":"Luxembourg","MT":"Malta",
    "CY":"Cyprus","NZ":"New Zealand","HK":"Hong Kong","MO":"Macau","LK":"Sri Lanka","NP":"Nepal","BT":"Bhutan",
    "MV":"Maldives","BN":"Brunei","TL":"Timor-Leste","PG":"Papua New Guinea","FJ":"Fiji","MN":"Mongolia",
    "KZ":"Kazakhstan","UZ":"Uzbekistan","KG":"Kyrgyzstan","TJ":"Tajikistan","TM":"Turkmenistan","AZ":"Azerbaijan",
    "GE":"Georgia","AM":"Armenia","IL":"Israel","JO":"Jordan","LB":"Lebanon","IQ":"Iraq","IR":"Iran","KW":"Kuwait",
    "QA":"Qatar","BH":"Bahrain","OM":"Oman","YE":"Yemen","SY":"Syria","PS":"Palestine","MA":"Morocco","TN":"Tunisia",
    "LY":"Libya","SD":"Sudan","KE":"Kenya","TZ":"Tanzania","UG":"Uganda","ET":"Ethiopia","GH":"Ghana","CI":"Côte d'Ivoire",
    "SN":"Senegal","CM":"Cameroon","AO":"Angola","MZ":"Mozambique","ZM":"Zambia","BW":"Botswana","NA":"Namibia",
    "RW":"Rwanda","MU":"Mauritius","MG":"Madagascar","CD":"DR Congo","CG":"Congo","GA":"Gabon","ML":"Mali",
    "BF":"Burkina Faso","NE":"Niger","BJ":"Benin","TG":"Togo","GN":"Guinea","SL":"Sierra Leone","LR":"Liberia",
    "MW":"Malawi","SO":"Somalia","BO":"Bolivia","PY":"Paraguay","UY":"Uruguay","PA":"Panama","NI":"Nicaragua",
    "HN":"Honduras","SV":"El Salvador","BZ":"Belize","GY":"Guyana","SR":"Suriname","BS":"Bahamas","BB":"Barbados",
    "CW":"Curaçao","AW":"Aruba","PR":"Puerto Rico","GD":"Grenada","LC":"Saint Lucia","VC":"St Vincent & Gren.",
    "AG":"Antigua & Barbuda","DM":"Dominica","KN":"St Kitts & Nevis","CN":"China","BA":"Bosnia & Herzegovina",
    "MK":"North Macedonia","AL":"Albania","ME":"Montenegro","XK":"Kosovo","MD":"Moldova","BY":"Belarus","AF":"Afghanistan",
}
