// AUTO-GENERATED by payments-automation/run.py — do not edit by hand.
// Mirrors the Summary tab of loyverse_payments_analysis_ful_V2.xlsx.
window.MARGINS = {
  "updated": "2026-07-22",
  "title": "Loyverse Embedded Payments — Full True-Cost & Margin Analysis",
  "subtitle": "Apr 13–Jul 22, 2026 · 8,685 succeeded transactions · 15 merchants · USD (29 EUR txns at face value)",
  "kpis": {
    "txns": 8685.0,
    "tpv": 142434.94,
    "avgTicket": 16.4001082325849,
    "revenue": 3966.56,
    "takeRate": 0.0278482231957973,
    "totalFees": 3676.8362,
    "netMargin": 289.7238,
    "netTakeRate": 0.00203407815526162,
    "pctProfitable": 0.396660909614277,
    "profitableTxns": 3445.0,
    "unprofitableTxns": 5240.0,
    "withActual": 8576.0,
    "withEstimated": 109.0,
    "failed": 125.0
  },
  "fees": {
    "total": 3676.8362,
    "network": {
      "label": "    Network Fees (pass-through)",
      "total": 3077.4262,
      "items": [
        {
          "label": "        Interchange",
          "value": 2515.066
        },
        {
          "label": "        Card Scheme Fees",
          "value": 393.4939
        },
        {
          "label": "        Amex Discount",
          "value": 168.8663
        }
      ]
    },
    "stripe": {
      "label": "    Stripe Fees (markup)",
      "total": 599.41,
      "items": [
        {
          "label": "        Per Auth Fee",
          "value": 438.11
        },
        {
          "label": "        Volume Fee",
          "value": 140.23
        }
      ]
    }
  },
  "extraFees": [
    {
      "label": "        Radar (Fraud) Fee",
      "value": 0.07
    },
    {
      "label": "        Tap to Pay Fee",
      "value": 5.71
    },
    {
      "label": "        Standard Payout Fee",
      "value": 4.27
    },
    {
      "label": "        Terminal Use Fee",
      "value": 11.02
    },
    {
      "label": "        Account Volume Fee",
      "value": 0.0
    }
  ],
  "scenarios": {
    "headers": {
      "name": "Scenario",
      "revenue": "Revenue"
    },
    "rows": [
      {
        "name": "Current mix",
        "revenue": 3966.56
      },
      {
        "name": "All 2.5% flat",
        "revenue": 3560.8735
      },
      {
        "name": "All 2.5% + 5¢",
        "revenue": 3995.1235
      },
      {
        "name": "All 2.6% + 10¢",
        "revenue": 4571.80844
      },
      {
        "name": "All 2.6% + 15¢",
        "revenue": 5006.05844
      },
      {
        "name": "All 2.8% + 15¢",
        "revenue": 5290.92832
      }
    ]
  },
  "notes": {
    "settlement": "Note: Apr–Jul 19 have complete IC+ cost data; the most recent charges are still settling, so their cost is estimated from each charge’s card-brand × funding blended rate. Amounts are net of Amex/network discounts.",
    "scenario": "Monthly/annual scaled from the 99-day sample (Apr 13–Jul 21); cost held constant across scenarios."
  }
};
