// AUTO-GENERATED by payments-automation/run.py — do not edit by hand.
// Mirrors the Summary tab of loyverse_payments_analysis_ful_V2.xlsx.
window.MARGINS = {
  "updated": "2026-08-03",
  "title": "Loyverse Embedded Payments — Full True-Cost & Margin Analysis",
  "subtitle": "Apr 13–Aug 3, 2026 · 11,014 succeeded transactions · 40 merchants · USD (29 EUR txns at face value)",
  "kpis": {
    "txns": 11014.0,
    "tpv": 211127.0,
    "avgTicket": 19.168966769566,
    "revenue": 5938.9,
    "takeRate": 0.0281295144628588,
    "totalFees": 5158.9254,
    "netMargin": 779.9746,
    "netTakeRate": 0.00369433847873555,
    "pctProfitable": 0.435808970401307,
    "profitableTxns": 4800.0,
    "unprofitableTxns": 6214.0,
    "withActual": 10524.0,
    "withEstimated": 490.0,
    "failed": 207.0
  },
  "fees": {
    "total": 5158.9254,
    "network": {
      "label": "    Network Fees (pass-through)",
      "total": 4357.3754,
      "items": [
        {
          "label": "        Interchange",
          "value": 3618.7906
        },
        {
          "label": "        Card Scheme Fees",
          "value": 532.8385
        },
        {
          "label": "        Amex Discount",
          "value": 205.7463
        }
      ]
    },
    "stripe": {
      "label": "    Stripe Fees (markup)",
      "total": 801.55,
      "items": [
        {
          "label": "        Per Auth Fee",
          "value": 555.47
        },
        {
          "label": "        Volume Fee",
          "value": 205.29
        }
      ]
    }
  },
  "extraFees": [
    {
      "label": "        Radar (Fraud) Fee",
      "value": 0.13
    },
    {
      "label": "        Tap to Pay Fee",
      "value": 20.67
    },
    {
      "label": "        Standard Payout Fee",
      "value": 8.97
    },
    {
      "label": "        Terminal Use Fee",
      "value": 11.02
    },
    {
      "label": "        Account Volume Fee",
      "value": 0.0
    }
  ],
  "scenarios": {
    "headers": {
      "name": "Scenario",
      "revenue": "Revenue"
    },
    "rows": [
      {
        "name": "Current mix",
        "revenue": 5938.9
      },
      {
        "name": "All 2.5% flat",
        "revenue": 5278.175
      },
      {
        "name": "All 2.5% + 5¢",
        "revenue": 5828.875
      },
      {
        "name": "All 2.6% + 10¢",
        "revenue": 6590.702
      },
      {
        "name": "All 2.6% + 15¢",
        "revenue": 7141.402
      },
      {
        "name": "All 2.8% + 15¢",
        "revenue": 7563.656
      }
    ]
  },
  "notes": {
    "settlement": "Note: Apr–Jul 19 have complete IC+ cost data; the most recent charges are still settling, so their cost is estimated from each charge’s card-brand × funding blended rate. Amounts are net of Amex/network discounts.",
    "scenario": "Monthly/annual scaled from the 99-day sample (Apr 13–Jul 21); cost held constant across scenarios."
  }
};
