// AUTO-GENERATED by payments-automation/run.py — do not edit by hand.
// Mirrors the Summary tab of loyverse_payments_analysis_ful_V2.xlsx.
window.MARGINS = {
  "updated": "2026-08-12",
  "title": "Loyverse Embedded Payments — Full True-Cost & Margin Analysis",
  "subtitle": "Apr 13–Aug 12, 2026 · 13,455 succeeded transactions · 51 merchants · USD (29 EUR txns at face value)",
  "kpis": {
    "txns": 13455.0,
    "tpv": 279061.71,
    "avgTicket": 20.7403723522854,
    "revenue": 7938.71,
    "takeRate": 0.0284478655276641,
    "totalFees": 6874.9678,
    "netMargin": 1063.7422,
    "netTakeRate": 0.00381185294105737,
    "pctProfitable": 0.466369379412858,
    "profitableTxns": 6275.0,
    "unprofitableTxns": 7180.0,
    "withActual": 13158.0,
    "withEstimated": 297.0,
    "failed": 302.0
  },
  "fees": {
    "total": 6874.9678,
    "network": {
      "label": "    Network Fees (pass-through)",
      "total": 5852.2978,
      "items": [
        {
          "label": "        Interchange",
          "value": 4868.3203
        },
        {
          "label": "        Card Scheme Fees",
          "value": 723.4066
        },
        {
          "label": "        Amex Discount",
          "value": 260.5709
        }
      ]
    },
    "stripe": {
      "label": "    Stripe Fees (markup)",
      "total": 1022.67,
      "items": [
        {
          "label": "        Per Auth Fee",
          "value": 684.92
        },
        {
          "label": "        Volume Fee",
          "value": 275.28
        }
      ]
    }
  },
  "extraFees": [
    {
      "label": "        Radar (Fraud) Fee",
      "value": 0.13
    },
    {
      "label": "        Tap to Pay Fee",
      "value": 42.35
    },
    {
      "label": "        Standard Payout Fee",
      "value": 8.97
    },
    {
      "label": "        Terminal Use Fee",
      "value": 11.02
    },
    {
      "label": "        Account Volume Fee",
      "value": 0.0
    }
  ],
  "scenarios": {
    "headers": {
      "name": "Scenario",
      "revenue": "Revenue"
    },
    "rows": [
      {
        "name": "Current mix",
        "revenue": 7938.71
      },
      {
        "name": "All 2.5% flat",
        "revenue": 6976.54275
      },
      {
        "name": "All 2.5% + 5¢",
        "revenue": 7649.29275
      },
      {
        "name": "All 2.6% + 10¢",
        "revenue": 8601.10446
      },
      {
        "name": "All 2.6% + 15¢",
        "revenue": 9273.85446
      },
      {
        "name": "All 2.8% + 15¢",
        "revenue": 9831.97788
      }
    ]
  },
  "notes": {
    "settlement": "Note: Apr–Jul 19 have complete IC+ cost data; the most recent charges are still settling, so their cost is estimated from each charge’s card-brand × funding blended rate. Amounts are net of Amex/network discounts.",
    "scenario": "Monthly/annual scaled from the 99-day sample (Apr 13–Jul 21); cost held constant across scenarios."
  }
};
