"""Reader for activated-payments/activation-data.js.

That file is regenerated by activated-payments/pull.js from the Stripe data share in
Snowflake (CONNECTED_ACCOUNTS) roughly every three hours and committed to master.
Its `status` field is derived in pull.js:statusOf() as:

    charges_enabled == true                 -> "Enabled"
    disabled_reason startswith "rejected"   -> "Rejected"
    otherwise                               -> "Restricted"

so `status == "Enabled"` is exactly `charges_enabled == true`. That equivalence is the
reason the committed history of this file can be replayed into a genuine enablement
event ledger (see ledger.py) instead of guessing enablement from a TOS proxy.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

# window.__ACT = [ ... ];
_ACT_RE = re.compile(r"window\.__ACT\s*=\s*(\[.*?\])\s*;\s*$", re.S | re.M)
_STAMP_RE = re.compile(r'window\.__ACT_LAST_UPDATED\s*=\s*"([^"]+)"')

ENABLED = "Enabled"


class ActivationParseError(ValueError):
    """activation-data.js did not contain a parseable __ACT array."""


@dataclass(frozen=True)
class ActivationSnapshot:
    """One parsed revision of activation-data.js."""

    rows: list[dict[str, Any]]
    last_updated: str | None

    def by_account(self) -> dict[str, dict[str, Any]]:
        """Index rows by Stripe account id.

        Deduplication is by exact `acct` value only — never by merchant display name,
        which is neither unique nor stable.
        """
        return {r["acct"]: r for r in self.rows if r.get("acct")}

    def statuses(self) -> dict[str, str]:
        return {r["acct"]: r.get("status", "") for r in self.rows if r.get("acct")}


def parse(source: str) -> ActivationSnapshot:
    """Parse the text of an activation-data.js revision."""
    match = _ACT_RE.search(source)
    if not match:
        raise ActivationParseError("no `window.__ACT = [...]` array found")
    rows = json.loads(match.group(1))
    if not isinstance(rows, list):
        raise ActivationParseError("__ACT is not a list")
    stamp = _STAMP_RE.search(source)
    return ActivationSnapshot(rows=rows, last_updated=stamp.group(1) if stamp else None)


def load(path: str) -> ActivationSnapshot:
    with open(path, encoding="utf-8") as handle:
        return parse(handle.read())
